spring:
  application:
    name: WebPush
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resource/static/
thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html